print("------------")
print("Repeat 1.2.2")
print("-------------------------")
print("Update log for Update 1.2")
print("(1.2) Added update log")
print("(1.2.1) Beautification")
print("(1.2.2) Added instant and instant disclaimer, as well as removed the thinking message when enter is pressed")
print("-----------------------------------------------------------------------------")
print("Type something and press ENTER to have it instantly* repeated!")
print("-----------------------------------------------------------------------------")
print("*instantly depends on your device's speed, if you device is something like an apple 2 running python3 somehow its not gonna be very instant.")
print("-----------------------------------------------------------------------------")
message = input("")
print("---------------------------------------------------------------------------")
print("Repeating.")
print("----------")
print("You said...")
print(message)
print("--------------------")
print("repeat 1.2.2 stopped")
print("--------------------")