print("------------")
import time
time.sleep(1)
print("Repeat 1.3")
time.sleep(1)
print("-------------------------")
time.sleep(0.5)
print("Update log for Update 1.3: The Time Update")
time.sleep(0.3)
print("(1.3) Its time for the Time Update! Added time delays for elegance!")
time.sleep(0.5)
print("-----------------------------------------------------------------------------")
time.sleep(1)
print("Type something and press ENTER to have it instantly* repeated!")
time.sleep(1)
print("-----------------------------------------------------------------------------")
time.sleep(0.5)
print("*instantly depends on your device's speed, if you device is something like an apple 2 running python3 somehow its not gonna be very instant.")
time.sleep(0.5)
print("-----------------------------------------------------------------------------")
time.sleep(0.3)
message = input("")
time.sleep(0.75)
print("---------------------------------------------------------------------------")
time.sleep(0.5)
print("Repeating.")
time.sleep(0.5)
print("----------")
time.sleep(0.5)
print("You said...")
time.sleep(0.75)
print(message)
time.sleep(1)
print("--------------------")
time.sleep(0.5)
print("repeat 1.2.2 stopped")
time.sleep(0.5)
print("--------------------")