print("------------")
import time
time.sleep(1)
print("Repeat 1.3.1")
time.sleep(1)
print("-------------------------")
time.sleep(0.5)
print("Update log for Update 1.3: The Time Update")
time.sleep(0.3)
print("(1.3) Its time for the Time Update! Added time delays for elegance!")
time.sleep(0.5)
print("(1.3.1) Removed the instant thing and updated version at end.")
time.sleep(0.5)
print("-----------------------------------------------------------------------------")
time.sleep(0.5)
print("Type something to have it repeated!")
time.sleep(0.5)
print("-----------------------------------------------------------------------------")
time.sleep(0.3)
message = input("")
time.sleep(0.75)
print("---------------------------------------------------------------------------")
time.sleep(0.5)
print("Repeating.")
time.sleep(0.5)
print("----------")
time.sleep(0.5)
print("You said...")
time.sleep(0.75)
print(message)
time.sleep(1)
print("--------------------")
time.sleep(0.5)
print("repeat 1.3.1 stopped")
time.sleep(0.5)
print("--------------------")